
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Apr 16 2023 02:00:16 IST (Apr 15 2023 20:30:16 UTC)

// Verification Directory fv/top_DDR_controller 

module top_DDR_controller(clk, reset, WR_command, DRAM_Address,
     Write_data, Read_data, valid_data, dram_ras, dram_cas, dram_dqs,
     dq, w_en, busy, cmd_exec_ack, d_addr, refresh_request);
  input clk, reset, WR_command;
  input [10:0] DRAM_Address;
  input [15:0] Write_data;
  output [15:0] Read_data;
  output valid_data, dram_ras, dram_cas, dram_dqs, w_en, busy,
       cmd_exec_ack, refresh_request;
  output [5:0] d_addr;
  inout [7:0] dq;
  wire clk, reset, WR_command;
  wire [10:0] DRAM_Address;
  wire [15:0] Write_data;
  wire [15:0] Read_data;
  wire valid_data, dram_ras, dram_cas, dram_dqs, w_en, busy,
       cmd_exec_ack, refresh_request;
  wire [5:0] d_addr;
  wire [7:0] dq;
  wire [3:0] controller_state;
  wire [5:0] write_burst_count;
  wire [5:0] \active_row[0] ;
  wire [5:0] \active_row[1] ;
  wire [5:0] \active_row[2] ;
  wire [5:0] \active_row[3] ;
  wire [7:0] dram_wr_data;
  wire [3:0] next_controller_state;
  wire [3:0] open_row;
  wire [5:0] row_addr;
  wire [13:0] refresh_counter;
  wire [5:0] column_addr;
  wire [15:0] \temp_write_data[3] ;
  wire [15:0] \temp_write_data[1] ;
  wire [15:0] \temp_write_data[0] ;
  wire [15:0] \temp_write_data[2] ;
  wire [8:0] REF_counter;
  wire [8:0] PRE_counter;
  wire [8:0] RCD_counter;
  wire [8:0] CAS_counter;
  wire [8:0] BURST_counter;
  wire [5:0] bank_id;
  wire [6:0] data_counter;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_140, n_141, n_142, n_143, n_144;
  wire n_145, n_146, n_147, n_148, n_149, n_150, n_151, n_152;
  wire n_153, n_154, n_155, n_156, n_157, n_158, n_159, n_160;
  wire n_161, n_163, n_164, n_165, n_166, n_167, n_168, n_169;
  wire n_170, n_171, n_172, n_173, n_174, n_175, n_176, n_177;
  wire n_178, n_179, n_180, n_181, n_182, n_183, n_184, n_185;
  wire n_186, n_187, n_188, n_189, n_190, n_191, n_192, n_193;
  wire n_194, n_195, n_196, n_197, n_198, n_199, n_200, n_201;
  wire n_202, n_203, n_204, n_205, n_206, n_207, n_208, n_209;
  wire n_210, n_211, n_212, n_213, n_214, n_215, n_216, n_217;
  wire n_218, n_219, n_220, n_221, n_222, n_223, n_224, n_225;
  wire n_226, n_227, n_228, n_229, n_230, n_231, n_232, n_233;
  wire n_234, n_235, n_236, n_237, n_238, n_239, n_240, n_241;
  wire n_242, n_243, n_244, n_245, n_246, n_247, n_248, n_249;
  wire n_250, n_251, n_252, n_253, n_254, n_255, n_256, n_257;
  wire n_258, n_259, n_260, n_261, n_262, n_263, n_264, n_265;
  wire n_266, n_267, n_268, n_269, n_270, n_271, n_272, n_273;
  wire n_274, n_275, n_276, n_277, n_278, n_279, n_280, n_281;
  wire n_282, n_283, n_284, n_285, n_286, n_287, n_288, n_289;
  wire n_292, n_294, n_295, n_296, n_297, n_298, n_299, n_300;
  wire n_301, n_302, n_303, n_304, n_305, n_306, n_307, n_308;
  wire n_309, n_310, n_311, n_312, n_313, n_314, n_315, n_316;
  wire n_317, n_318, n_319, n_320, n_321, n_322, n_323, n_324;
  wire n_325, n_326, n_330, n_337, n_339, n_363, n_365, n_366;
  wire n_367, n_368, n_369, temp_cmd;
  assign cmd_exec_ack = 1'b0;
  assign Read_data[0] = 1'b0;
  assign Read_data[1] = 1'b0;
  assign Read_data[2] = 1'b0;
  assign Read_data[3] = 1'b0;
  assign Read_data[4] = 1'b0;
  assign Read_data[5] = 1'b0;
  assign Read_data[6] = 1'b0;
  assign Read_data[7] = 1'b0;
  assign Read_data[8] = 1'b0;
  assign Read_data[9] = 1'b0;
  assign Read_data[10] = 1'b0;
  assign Read_data[11] = 1'b0;
  assign Read_data[12] = 1'b0;
  assign Read_data[13] = 1'b0;
  assign Read_data[14] = 1'b0;
  assign Read_data[15] = 1'b0;
  CKINVM2R g7720(.A (n_337), .Z (n_289));
  ND4B1M2R g7787__2398(.B (temp_cmd), .C (controller_state[1]), .D
       (controller_state[3]), .NA (n_303), .Z (n_337));
  NR4M1R g7788__5107(.A (write_burst_count[2]), .B
       (write_burst_count[3]), .C (write_burst_count[5]), .D
       (write_burst_count[4]), .Z (n_292));
  ND2B1M2R g7789__6260(.B (controller_state[0]), .NA
       (controller_state[2]), .Z (n_303));
  LACQM2RA \active_row_reg[0][0] (.GB (n_197), .D (n_158), .Q
       (\active_row[0] [0]));
  LACQM2RA \active_row_reg[0][1] (.GB (n_197), .D (n_157), .Q
       (\active_row[0] [1]));
  LACQM2RA \active_row_reg[0][2] (.GB (n_197), .D (n_156), .Q
       (\active_row[0] [2]));
  LACQM2RA \active_row_reg[0][3] (.GB (n_197), .D (n_159), .Q
       (\active_row[0] [3]));
  LACQM2RA \active_row_reg[0][4] (.GB (n_197), .D (n_160), .Q
       (\active_row[0] [4]));
  LACQM2RA \active_row_reg[0][5] (.GB (n_197), .D (n_146), .Q
       (\active_row[0] [5]));
  LACQM2RA \active_row_reg[1][0] (.GB (n_195), .D (n_158), .Q
       (\active_row[1] [0]));
  LACQM2RA \active_row_reg[1][1] (.GB (n_195), .D (n_157), .Q
       (\active_row[1] [1]));
  LACQM2RA \active_row_reg[1][2] (.GB (n_195), .D (n_156), .Q
       (\active_row[1] [2]));
  LACQM2RA \active_row_reg[1][3] (.GB (n_195), .D (n_159), .Q
       (\active_row[1] [3]));
  LACQM2RA \active_row_reg[1][4] (.GB (n_195), .D (n_160), .Q
       (\active_row[1] [4]));
  LACQM2RA \active_row_reg[1][5] (.GB (n_195), .D (n_146), .Q
       (\active_row[1] [5]));
  LACQM2RA \active_row_reg[2][0] (.GB (n_198), .D (n_158), .Q
       (\active_row[2] [0]));
  LACQM2RA \active_row_reg[2][1] (.GB (n_198), .D (n_157), .Q
       (\active_row[2] [1]));
  LACQM2RA \active_row_reg[2][2] (.GB (n_198), .D (n_156), .Q
       (\active_row[2] [2]));
  LACQM2RA \active_row_reg[2][3] (.GB (n_198), .D (n_159), .Q
       (\active_row[2] [3]));
  LACQM2RA \active_row_reg[2][4] (.GB (n_198), .D (n_160), .Q
       (\active_row[2] [4]));
  LACQM2RA \active_row_reg[2][5] (.GB (n_198), .D (n_146), .Q
       (\active_row[2] [5]));
  LACQM2RA \active_row_reg[3][0] (.GB (n_196), .D (n_158), .Q
       (\active_row[3] [0]));
  LACQM2RA \active_row_reg[3][1] (.GB (n_196), .D (n_157), .Q
       (\active_row[3] [1]));
  LACQM2RA \active_row_reg[3][2] (.GB (n_196), .D (n_156), .Q
       (\active_row[3] [2]));
  LACQM2RA \active_row_reg[3][3] (.GB (n_196), .D (n_159), .Q
       (\active_row[3] [3]));
  LACQM2RA \active_row_reg[3][4] (.GB (n_196), .D (n_160), .Q
       (\active_row[3] [4]));
  LACQM2RA \active_row_reg[3][5] (.GB (n_196), .D (n_146), .Q
       (\active_row[3] [5]));
  LACQM2RA \dram_wr_data_reg[0] (.GB (n_267), .D (n_257), .Q
       (dram_wr_data[0]));
  LACQM2RA \dram_wr_data_reg[1] (.GB (n_267), .D (n_258), .Q
       (dram_wr_data[1]));
  LACQM2RA \dram_wr_data_reg[2] (.GB (n_267), .D (n_252), .Q
       (dram_wr_data[2]));
  LACQM2RA \dram_wr_data_reg[3] (.GB (n_267), .D (n_253), .Q
       (dram_wr_data[3]));
  LACQM2RA \dram_wr_data_reg[4] (.GB (n_267), .D (n_254), .Q
       (dram_wr_data[4]));
  LACQM2RA \dram_wr_data_reg[5] (.GB (n_267), .D (n_251), .Q
       (dram_wr_data[5]));
  LACQM2RA \dram_wr_data_reg[6] (.GB (n_267), .D (n_255), .Q
       (dram_wr_data[6]));
  LACQM2RA \dram_wr_data_reg[7] (.GB (n_267), .D (n_250), .Q
       (dram_wr_data[7]));
  LAQM2RA \next_controller_state_reg[0] (.G (n_288), .D (n_283), .Q
       (next_controller_state[0]));
  LAQM2RA \next_controller_state_reg[1] (.G (n_288), .D (n_287), .Q
       (next_controller_state[1]));
  LAQM2RA \next_controller_state_reg[2] (.G (n_288), .D (n_286), .Q
       (next_controller_state[2]));
  LAQM2RA \next_controller_state_reg[3] (.G (n_288), .D (n_280), .Q
       (next_controller_state[3]));
  LAQM2RA \open_row_reg[0] (.G (n_228), .D (n_176), .Q (open_row[0]));
  LAQM2RA \open_row_reg[1] (.G (n_231), .D (n_176), .Q (open_row[1]));
  LAQM2RA \open_row_reg[2] (.G (n_230), .D (n_176), .Q (open_row[2]));
  LAQM2RA \open_row_reg[3] (.G (n_229), .D (n_176), .Q (open_row[3]));
  LACQM2RA valid_data_reg(.GB (n_166), .D (n_166), .Q (valid_data));
  ND4M1R g10580__4319(.A (n_178), .B (n_325), .C (n_285), .D (n_323),
       .Z (n_287));
  NR4B1M1R g10581__8428(.B (n_284), .C (n_155), .D (n_180), .NA
       (n_172), .Z (n_286));
  NR3B1M1R g10583__5526(.B (n_155), .C (n_179), .NA (n_282), .Z
       (n_285));
  ND4M1R g10584__6783(.A (n_279), .B (n_178), .C (n_275), .D (n_147),
       .Z (n_284));
  OA211M2RA g10585__3680(.A1 (n_303), .A2 (n_168), .B (n_281), .C
       (n_365), .Z (n_283));
  AOI222M1RA g10587__1617(.A1 (n_8), .A2 (controller_state[1]), .B1
       (n_171), .B2 (n_278), .C1 (n_132), .C2 (n_140), .Z (n_282));
  NR4M1R g10588__2802(.A (n_132), .B (n_155), .C (n_180), .D (n_133),
       .Z (n_281));
  ND3M1R g10589__1705(.A (n_178), .B (n_323), .C (n_277), .Z (n_280));
  AOI31M1R g10590__5122(.A1 (n_171), .A2 (n_276), .A3 (n_274), .B
       (n_179), .Z (n_279));
  OAI221M1R g10591__8246(.A1 (n_136), .A2 (n_269), .B1 (n_271), .B2
       (WR_command), .C (n_276), .Z (n_278));
  OA211M2RA g10592__7098(.A1 (n_136), .A2 (n_300), .B (n_181), .C
       (n_275), .Z (n_277));
  AO31M1RA g10593__6131(.A1 (n_273), .A2 (n_268), .A3 (n_266), .B
       (n_271), .Z (n_276));
  ND3M1R g10595__1881(.A (n_171), .B (n_269), .C (refresh_request), .Z
       (n_275));
  OA21M1RA g10596__5115(.A1 (n_141), .A2 (n_271), .B (n_136), .Z
       (n_274));
  AOI211M1R g10599__7482(.A1 (row_addr[0]), .A2 (n_244), .B (n_256), .C
       (n_270), .Z (n_273));
  NR4B1M1R g10600__4733(.B (reset), .C (refresh_counter[13]), .D
       (n_301), .NA (n_330), .Z (n_272));
  OAI21B20M1R g10601__6161(.B (cmd_exec_ack), .NA1 (n_261), .NA2
       (n_260), .Z (n_271));
  OAI211M1R g10602__9315(.A1 (row_addr[2]), .A2 (n_247), .B (n_264), .C
       (n_265), .Z (n_270));
  BUFTM2R g162__9945(.A (dram_wr_data[0]), .E (WR_command), .Z (dq[0]));
  BUFTM2R g157__2883(.A (dram_wr_data[5]), .E (WR_command), .Z (dq[5]));
  BUFTM2R g158__2346(.A (dram_wr_data[4]), .E (WR_command), .Z (dq[4]));
  BUFTM2R g159__1666(.A (dram_wr_data[3]), .E (WR_command), .Z (dq[3]));
  BUFTM2R g160__7410(.A (dram_wr_data[2]), .E (WR_command), .Z (dq[2]));
  BUFTM2R g161__6417(.A (dram_wr_data[1]), .E (WR_command), .Z (dq[1]));
  BUFTM2R g156__5477(.A (dram_wr_data[6]), .E (WR_command), .Z (dq[6]));
  AO222M1RA g10603__2398(.A1 (n_170), .A2 (n_245), .B1 (n_177), .B2
       (column_addr[1]), .C1 (n_169), .C2 (row_addr[1]), .Z
       (d_addr[1]));
  AOI21M1R g10604__5107(.A1 (n_249), .A2 (row_addr[5]), .B (n_259), .Z
       (n_268));
  BUFTM2R g1__6260(.A (dram_wr_data[7]), .E (WR_command), .Z (dq[7]));
  OAI21B20M1R g10605__4319(.B (n_262), .NA1 (column_addr[0]), .NA2
       (n_177), .Z (d_addr[0]));
  OAI21B20M1R g10606__8428(.B (n_263), .NA1 (column_addr[2]), .NA2
       (n_177), .Z (d_addr[2]));
  NR4M1R g10607__5526(.A (open_row[0]), .B (open_row[1]), .C
       (open_row[3]), .D (open_row[2]), .Z (n_269));
  ND4M1R g10608__6783(.A (n_243), .B (n_165), .C (controller_state[3]),
       .D (n_367), .Z (n_288));
  MOAI22M1RA g10617__3680(.A1 (n_300), .A2 (n_249), .B1 (n_169), .B2
       (row_addr[5]), .Z (d_addr[5]));
  OR2M2R g10618__1617(.A (refresh_counter[12]), .B (n_304), .Z (n_301));
  MAOI22M1RA g10619__2802(.A1 (n_246), .A2 (row_addr[4]), .B1 (n_249),
       .B2 (row_addr[5]), .Z (n_266));
  MAOI22M1RA g10620__1705(.A1 (n_248), .A2 (row_addr[3]), .B1 (n_248),
       .B2 (row_addr[3]), .Z (n_265));
  MAOI22M1RA g10621__5122(.A1 (n_247), .A2 (row_addr[2]), .B1 (n_246),
       .B2 (row_addr[4]), .Z (n_264));
  MOAI22M1RA g10622__8246(.A1 (n_300), .A2 (n_248), .B1 (n_169), .B2
       (row_addr[3]), .Z (d_addr[3]));
  MAOI22M1RA g10623__7098(.A1 (n_169), .A2 (row_addr[2]), .B1 (n_300),
       .B2 (n_247), .Z (n_263));
  MOAI22M1RA g10624__6131(.A1 (n_300), .A2 (n_246), .B1 (n_169), .B2
       (row_addr[4]), .Z (d_addr[4]));
  MAOI22M1RA g10625__1881(.A1 (n_169), .A2 (row_addr[0]), .B1 (n_300),
       .B2 (n_244), .Z (n_262));
  AOI22M1R g10626__5115(.A1 (n_152), .A2 (open_row[2]), .B1
       (open_row[3]), .B2 (n_150), .Z (n_261));
  AOI22M1R g10627__7482(.A1 (n_145), .A2 (open_row[0]), .B1
       (open_row[1]), .B2 (n_143), .Z (n_260));
  MAOI22M1RA g10628__4733(.A1 (n_245), .A2 (row_addr[1]), .B1 (n_245),
       .B2 (row_addr[1]), .Z (n_259));
  OAI22M2R g10629__6161(.A1 (n_154), .A2 (n_239), .B1 (n_153), .B2
       (n_240), .Z (n_258));
  OAI211M2R g10630__9315(.A1 (n_153), .A2 (n_241), .B (n_225), .C
       (n_224), .Z (n_257));
  NR2M1R g10631__9945(.A (row_addr[0]), .B (n_244), .Z (n_256));
  OAI22M2R g10632__2883(.A1 (n_154), .A2 (n_233), .B1 (n_153), .B2
       (n_234), .Z (n_255));
  OR2M2R g10633__2346(.A (refresh_counter[11]), .B (n_299), .Z (n_304));
  OAI211M2R g10634__1666(.A1 (n_153), .A2 (n_236), .B (n_218), .C
       (n_217), .Z (n_254));
  OAI211M2R g10635__7410(.A1 (n_153), .A2 (n_237), .B (n_219), .C
       (n_221), .Z (n_253));
  OAI211M2R g10636__6417(.A1 (n_153), .A2 (n_238), .B (n_223), .C
       (n_222), .Z (n_252));
  OAI211M2R g10637__5477(.A1 (n_153), .A2 (n_242), .B (n_214), .C
       (n_216), .Z (n_251));
  OAI211M2R g10638__2398(.A1 (n_153), .A2 (n_232), .B (n_213), .C
       (n_211), .Z (n_250));
  OR2M2R g10643__5107(.A (refresh_counter[10]), .B (n_319), .Z (n_299));
  AOI221M1R g10644__6260(.A1 (n_152), .A2 (\active_row[2] [5]), .B1
       (n_150), .B2 (\active_row[3] [5]), .C (n_215), .Z (n_249));
  OA32M1RA g10645__4319(.A1 (controller_state[1]), .A2
       (controller_state[2]), .A3 (n_302), .B1 (n_365), .B2 (n_330), .Z
       (n_243));
  AOI221M1R g10646__8428(.A1 (n_152), .A2 (\active_row[2] [3]), .B1
       (n_150), .B2 (\active_row[3] [3]), .C (n_226), .Z (n_248));
  AOI221M1R g10647__5526(.A1 (n_152), .A2 (\active_row[2] [2]), .B1
       (n_150), .B2 (\active_row[3] [2]), .C (n_220), .Z (n_247));
  AOI221M1R g10648__6783(.A1 (n_152), .A2 (\active_row[2] [4]), .B1
       (n_150), .B2 (\active_row[3] [4]), .C (n_227), .Z (n_246));
  AO221M1RA g10649__3680(.A1 (n_152), .A2 (\active_row[2] [1]), .B1
       (n_150), .B2 (\active_row[3] [1]), .C (n_212), .Z (n_245));
  AOI221M1R g10650__1617(.A1 (n_152), .A2 (\active_row[2] [0]), .B1
       (n_150), .B2 (\active_row[3] [0]), .C (n_235), .Z (n_244));
  AOI221M2R g10651__2802(.A1 (\temp_write_data[3] [5]), .A2 (n_187),
       .B1 (\temp_write_data[3] [13]), .B2 (n_189), .C (n_202), .Z
       (n_242));
  AOI221M2R g10652__1705(.A1 (\temp_write_data[3] [0]), .A2 (n_187),
       .B1 (\temp_write_data[3] [8]), .B2 (n_189), .C (n_206), .Z
       (n_241));
  AOI221M2R g10653__5122(.A1 (\temp_write_data[3] [1]), .A2 (n_187),
       .B1 (\temp_write_data[3] [9]), .B2 (n_189), .C (n_208), .Z
       (n_240));
  AOI221M2R g10654__8246(.A1 (\temp_write_data[1] [1]), .A2 (n_187),
       .B1 (\temp_write_data[1] [9]), .B2 (n_189), .C (n_209), .Z
       (n_239));
  AOI221M2R g10655__7098(.A1 (\temp_write_data[3] [2]), .A2 (n_187),
       .B1 (\temp_write_data[3] [10]), .B2 (n_189), .C (n_199), .Z
       (n_238));
  AOI221M2R g10656__6131(.A1 (\temp_write_data[3] [3]), .A2 (n_187),
       .B1 (\temp_write_data[3] [11]), .B2 (n_189), .C (n_204), .Z
       (n_237));
  AOI221M2R g10657__1881(.A1 (\temp_write_data[3] [4]), .A2 (n_187),
       .B1 (\temp_write_data[3] [12]), .B2 (n_189), .C (n_203), .Z
       (n_236));
  AO22M1RA g10658__5115(.A1 (\active_row[0] [0]), .A2 (n_145), .B1
       (n_143), .B2 (\active_row[1] [0]), .Z (n_235));
  AOI221M2R g10659__7482(.A1 (\temp_write_data[3] [6]), .A2 (n_187),
       .B1 (\temp_write_data[3] [14]), .B2 (n_189), .C (n_201), .Z
       (n_234));
  AOI221M2R g10660__4733(.A1 (\temp_write_data[1] [6]), .A2 (n_187),
       .B1 (\temp_write_data[1] [14]), .B2 (n_189), .C (n_200), .Z
       (n_233));
  AOI221M2R g10661__6161(.A1 (\temp_write_data[3] [7]), .A2 (n_187),
       .B1 (\temp_write_data[3] [15]), .B2 (n_189), .C (n_205), .Z
       (n_232));
  OAI21M1R g10662__9315(.A1 (n_185), .A2 (n_142), .B (n_210), .Z
       (n_231));
  OAI21M1R g10663__9945(.A1 (n_185), .A2 (n_151), .B (n_210), .Z
       (n_230));
  OAI21M1R g10664__2883(.A1 (n_185), .A2 (n_149), .B (n_210), .Z
       (n_229));
  OAI21M1R g10665__2346(.A1 (n_185), .A2 (n_144), .B (n_210), .Z
       (n_228));
  OR2M2R g10666__1666(.A (refresh_counter[9]), .B (n_320), .Z (n_319));
  NR2M1R g10667__7410(.A (reset), .B (n_207), .Z (n_267));
  AO22M1RA g10668__6417(.A1 (\active_row[0] [4]), .A2 (n_145), .B1
       (n_143), .B2 (\active_row[1] [4]), .Z (n_227));
  AO22M1RA g10669__5477(.A1 (\active_row[0] [3]), .A2 (n_145), .B1
       (n_143), .B2 (\active_row[1] [3]), .Z (n_226));
  AOI22M2R g10670__2398(.A1 (\temp_write_data[1] [0]), .A2 (n_134), .B1
       (\temp_write_data[1] [8]), .B2 (n_193), .Z (n_225));
  AOI22M2R g10671__5107(.A1 (\temp_write_data[0] [0]), .A2 (n_135), .B1
       (\temp_write_data[0] [8]), .B2 (n_194), .Z (n_224));
  AOI22M2R g10672__6260(.A1 (\temp_write_data[1] [2]), .A2 (n_134), .B1
       (\temp_write_data[1] [10]), .B2 (n_193), .Z (n_223));
  AOI22M2R g10673__4319(.A1 (\temp_write_data[0] [2]), .A2 (n_135), .B1
       (\temp_write_data[0] [10]), .B2 (n_194), .Z (n_222));
  AOI22M2R g10674__8428(.A1 (\temp_write_data[0] [3]), .A2 (n_135), .B1
       (\temp_write_data[0] [11]), .B2 (n_194), .Z (n_221));
  AO22M1RA g10675__5526(.A1 (\active_row[0] [2]), .A2 (n_145), .B1
       (n_143), .B2 (\active_row[1] [2]), .Z (n_220));
  AOI22M2R g10676__6783(.A1 (\temp_write_data[1] [3]), .A2 (n_134), .B1
       (\temp_write_data[1] [11]), .B2 (n_193), .Z (n_219));
  AOI22M2R g10677__3680(.A1 (\temp_write_data[1] [4]), .A2 (n_134), .B1
       (\temp_write_data[1] [12]), .B2 (n_193), .Z (n_218));
  AOI22M2R g10678__1617(.A1 (\temp_write_data[0] [4]), .A2 (n_135), .B1
       (\temp_write_data[0] [12]), .B2 (n_194), .Z (n_217));
  AOI22M2R g10679__2802(.A1 (\temp_write_data[0] [5]), .A2 (n_135), .B1
       (\temp_write_data[0] [13]), .B2 (n_194), .Z (n_216));
  AO22M1RA g10680__1705(.A1 (\active_row[0] [5]), .A2 (n_145), .B1
       (n_143), .B2 (\active_row[1] [5]), .Z (n_215));
  AOI22M2R g10681__5122(.A1 (\temp_write_data[1] [5]), .A2 (n_134), .B1
       (\temp_write_data[1] [13]), .B2 (n_193), .Z (n_214));
  AOI22M2R g10682__8246(.A1 (\temp_write_data[1] [7]), .A2 (n_134), .B1
       (\temp_write_data[1] [15]), .B2 (n_193), .Z (n_213));
  AO22M1RA g10683__7098(.A1 (\active_row[0] [1]), .A2 (n_145), .B1
       (n_143), .B2 (\active_row[1] [1]), .Z (n_212));
  AOI22M2R g10684__6131(.A1 (\temp_write_data[0] [7]), .A2 (n_135), .B1
       (\temp_write_data[0] [15]), .B2 (n_194), .Z (n_211));
  AO22M1RA g10685__1881(.A1 (n_190), .A2 (\temp_write_data[0] [1]), .B1
       (\temp_write_data[0] [9]), .B2 (n_191), .Z (n_209));
  AO22M1RA g10686__5115(.A1 (n_190), .A2 (\temp_write_data[2] [1]), .B1
       (\temp_write_data[2] [9]), .B2 (n_191), .Z (n_208));
  NR3B1M1R g10687__7482(.B (reset), .C (n_184), .NA (n_289), .Z
       (n_207));
  AO22M1RA g10688__4733(.A1 (n_190), .A2 (\temp_write_data[2] [0]), .B1
       (\temp_write_data[2] [8]), .B2 (n_191), .Z (n_206));
  OR2M2R g10689__6161(.A (refresh_counter[8]), .B (n_305), .Z (n_320));
  OR2M2R g10690__9315(.A (REF_counter[8]), .B (n_314), .Z (n_330));
  OAI211M1R g10691__9945(.A1 (reset), .A2 (n_172), .B (n_186), .C
       (n_175), .Z (n_210));
  AO22M1RA g10692__2883(.A1 (n_190), .A2 (\temp_write_data[2] [7]), .B1
       (\temp_write_data[2] [15]), .B2 (n_191), .Z (n_205));
  AO22M1RA g10693__2346(.A1 (n_190), .A2 (\temp_write_data[2] [3]), .B1
       (\temp_write_data[2] [11]), .B2 (n_191), .Z (n_204));
  AO22M1RA g10694__1666(.A1 (n_190), .A2 (\temp_write_data[2] [4]), .B1
       (\temp_write_data[2] [12]), .B2 (n_191), .Z (n_203));
  AO22M1RA g10695__7410(.A1 (n_190), .A2 (\temp_write_data[2] [5]), .B1
       (\temp_write_data[2] [13]), .B2 (n_191), .Z (n_202));
  AO22M1RA g10696__6417(.A1 (n_190), .A2 (\temp_write_data[2] [6]), .B1
       (\temp_write_data[2] [14]), .B2 (n_191), .Z (n_201));
  AO22M1RA g10697__5477(.A1 (n_190), .A2 (\temp_write_data[0] [6]), .B1
       (\temp_write_data[0] [14]), .B2 (n_191), .Z (n_200));
  AO22M1RA g10698__2398(.A1 (n_190), .A2 (\temp_write_data[2] [2]), .B1
       (\temp_write_data[2] [10]), .B2 (n_191), .Z (n_199));
  OR2M2R g10723__5107(.A (REF_counter[7]), .B (n_311), .Z (n_314));
  OR2M2R g10724__6260(.A (refresh_counter[7]), .B (n_306), .Z (n_305));
  NR2M2R g10725__4319(.A (n_154), .B (n_192), .Z (n_194));
  NR2M2R g10727__8428(.A (n_154), .B (n_188), .Z (n_193));
  INVM2R g10729(.A (n_191), .Z (n_192));
  INVM2R g10731(.A (n_188), .Z (n_189));
  OR2M2R g10733__5526(.A (refresh_counter[6]), .B (n_321), .Z (n_306));
  OR2M2R g10734__6783(.A (REF_counter[6]), .B (n_296), .Z (n_311));
  NR2M2R g10735__3680(.A (n_182), .B (n_369), .Z (n_191));
  NR2M2R g10736__1617(.A (n_183), .B (n_369), .Z (n_190));
  ND2M2R g10737__2802(.A (n_369), .B (n_183), .Z (n_188));
  NR2B1M2R g10738__1705(.B (n_183), .NA (n_369), .Z (n_187));
  INVM2R g10739(.A (n_185), .Z (n_186));
  AOI21B10M1R g10740__5122(.A1 (n_292), .B (n_182), .NA2 (dram_dqs), .Z
       (n_184));
  NR3B1M1R g10741__8246(.B (reset), .C (n_176), .NA (n_181), .Z
       (n_185));
  AOI21M1R g10742__7098(.A1 (n_143), .A2 (n_176), .B (reset), .Z
       (n_195));
  AOI21M1R g10743__6131(.A1 (n_150), .A2 (n_176), .B (reset), .Z
       (n_196));
  AOI21M1R g10744__1881(.A1 (n_152), .A2 (n_176), .B (reset), .Z
       (n_198));
  AOI21M1R g10745__5115(.A1 (n_145), .A2 (n_176), .B (reset), .Z
       (n_197));
  INVM2R g10746(.A (n_183), .Z (n_182));
  OR2M2R g10747__7482(.A (refresh_counter[5]), .B (n_307), .Z (n_321));
  ND2M2R g10748__4733(.A (dram_dqs), .B (n_292), .Z (n_183));
  OAI211B100M1R g10749__6161(.A1 (n_339), .B (n_365), .C (n_324), .NA2
       (n_132), .Z (dram_cas));
  OR2M2R g10750__9315(.A (REF_counter[5]), .B (n_312), .Z (n_296));
  CKINVM2R g10751(.A (n_325), .Z (n_180));
  AN2M2R g10752__9945(.A (n_165), .B (n_172), .Z (n_181));
  OR2M2R g10753__2883(.A (REF_counter[4]), .B (n_315), .Z (n_312));
  OR2M2R g10754__2346(.A (refresh_counter[4]), .B (n_308), .Z (n_307));
  BUFTM2R g2__1666(.A (clk), .E (n_173), .Z (dram_dqs));
  ND2M2R g10755__7410(.A (n_169), .B (n_366), .Z (n_325));
  INVM2R g10757(.A (n_176), .Z (n_175));
  NR2M1R g10758__6417(.A (temp_cmd), .B (n_363), .Z (n_179));
  OR2M2R g10759__5477(.A (cmd_exec_ack), .B (busy), .Z (n_368));
  ND2M1R g10760__2398(.A (n_174), .B (n_8), .Z (n_178));
  MOAI22M1RA g10761__5107(.A1 (n_164), .A2 (controller_state[3]), .B1
       (n_167), .B2 (controller_state[3]), .Z (n_177));
  NR2M1R g10762__6260(.A (reset), .B (n_363), .Z (n_176));
  INVM2R g10763(.A (n_174), .Z (n_326));
  BUFTM2R dram_clk_en_tri__4319(.A (1'b1), .E (n_163), .Z (n_173));
  OR2M2R g10764__8428(.A (PRE_counter[3]), .B (n_298), .Z (n_302));
  OR2M2R g10765__5526(.A (RCD_counter[3]), .B (n_310), .Z (n_366));
  OR2M2R g10766__6783(.A (REF_counter[3]), .B (n_313), .Z (n_315));
  OR2M2R g10767__3680(.A (refresh_counter[3]), .B (n_322), .Z (n_308));
  NR2M2R g10768__1617(.A (CAS_counter[3]), .B (n_317), .Z (n_174));
  INVM2R g10769(.A (n_171), .Z (busy));
  INVM1R g10770(.A (n_300), .Z (n_170));
  INVM2R g10771(.A (n_363), .Z (n_169));
  ND2M1R g10772__2802(.A (n_294), .B (n_161), .Z (dram_ras));
  ND2M2R g10773__1705(.A (n_163), .B (n_168), .Z (n_323));
  ND3M1R g10774__5122(.A (n_132), .B (controller_state[2]), .C
       (controller_state[1]), .Z (n_172));
  ND2M2R g10775__8246(.A (w_en), .B (controller_state[1]), .Z (n_365));
  NR2M2R g10776__7098(.A (controller_state[3]), .B (n_167), .Z (n_171));
  ND2B1M2R g10777__6131(.B (controller_state[3]), .NA (n_167), .Z
       (n_300));
  ND2M2R g10778__1881(.A (n_164), .B (n_137), .Z (n_363));
  OR2M2R g10780__5115(.A (CAS_counter[2]), .B (n_316), .Z (n_317));
  OR2M2R g10781__7482(.A (RCD_counter[2]), .B (n_297), .Z (n_310));
  OR2M2R g10782__4733(.A (PRE_counter[2]), .B (n_309), .Z (n_298));
  OR2M2R g10783__6161(.A (refresh_counter[2]), .B (n_318), .Z (n_322));
  OR2M2R g10784__9315(.A (BURST_counter[2]), .B (n_295), .Z (n_168));
  ND2M2R g10785__9945(.A (n_148), .B (n_140), .Z (n_167));
  INVM2R g10786(.A (n_163), .Z (n_367));
  INVM2R g10787(.A (n_324), .Z (n_8));
  OAI21M1R g10788__2883(.A1 (controller_state[1]), .A2
       (controller_state[3]), .B (n_148), .Z (n_161));
  NR2M2R g10789__2346(.A (controller_state[0]), .B (n_147), .Z (w_en));
  ND2M2R g10790__1666(.A (n_155), .B (n_137), .Z (n_294));
  ND2M1R g10791__7410(.A (n_155), .B (controller_state[3]), .Z (n_165));
  NR2M2R g10792__6417(.A (controller_state[0]), .B (n_339), .Z (n_164));
  OR3M2R g10793__5477(.A (REF_counter[1]), .B (REF_counter[0]), .C
       (REF_counter[2]), .Z (n_313));
  NR3M2R g10794__2398(.A (n_137), .B (n_140), .C (n_303), .Z (n_163));
  ND3B1M2R g10795__5107(.B (controller_state[2]), .C (n_137), .NA
       (controller_state[0]), .Z (n_324));
  INVM2R g10796(.A (n_152), .Z (n_151));
  INVM2R g10797(.A (n_149), .Z (n_150));
  NR2B1M1R g10798__6260(.B (reset), .NA (n_337), .Z (n_166));
  NR2B1M1R g10799__4319(.B (reset), .NA (row_addr[4]), .Z (n_160));
  NR2B1M1R g10800__8428(.B (reset), .NA (row_addr[3]), .Z (n_159));
  NR2B1M1R g10801__5526(.B (reset), .NA (row_addr[0]), .Z (n_158));
  NR2B1M1R g10802__6783(.B (reset), .NA (row_addr[1]), .Z (n_157));
  NR2B1M1R g10803__3680(.B (reset), .NA (row_addr[2]), .Z (n_156));
  NR2M2R g10804__1617(.A (controller_state[1]), .B (n_303), .Z (n_155));
  OR2M2R g10805__2802(.A (reset), .B (write_burst_count[1]), .Z
       (n_154));
  ND2M2R g10806__1705(.A (write_burst_count[1]), .B (n_9), .Z (n_153));
  NR2B1M1R g10807__5122(.B (bank_id[0]), .NA (bank_id[1]), .Z (n_152));
  ND2M1R g10808__8246(.A (bank_id[1]), .B (bank_id[0]), .Z (n_149));
  INVM2R g10809(.A (n_145), .Z (n_144));
  INVM2R g10810(.A (n_143), .Z (n_142));
  NR2M2R g10811__7098(.A (controller_state[0]), .B
       (controller_state[2]), .Z (n_148));
  OR2M2R g10812__6131(.A (RCD_counter[0]), .B (RCD_counter[1]), .Z
       (n_297));
  OR2M2R g10813__1881(.A (refresh_counter[0]), .B (refresh_counter[1]),
       .Z (n_318));
  CKND2M2R g10814__5115(.A (n_138), .B (controller_state[3]), .Z
       (n_147));
  OR2M2R g10815__7482(.A (BURST_counter[0]), .B (BURST_counter[1]), .Z
       (n_295));
  OR2M2R g10816__4733(.A (PRE_counter[1]), .B (PRE_counter[0]), .Z
       (n_309));
  OR2M2R g10817__6161(.A (CAS_counter[0]), .B (CAS_counter[1]), .Z
       (n_316));
  ND2M2R g10818__9315(.A (n_138), .B (controller_state[1]), .Z (n_339));
  AN2M2R g10819__9945(.A (row_addr[5]), .B (n_9), .Z (n_146));
  NR2M1R g10821__2883(.A (bank_id[0]), .B (bank_id[1]), .Z (n_145));
  NR2B1M1R g10822__2346(.B (bank_id[1]), .NA (bank_id[0]), .Z (n_143));
  INVM2R g10823(.A (WR_command), .Z (n_141));
  DFM2RA refresh_request_reg(.CK (clk), .D (n_272), .Q
       (refresh_request), .QB (n_136));
  NR2B1M2R g10831__1666(.B (n_154), .NA (n_190), .Z (n_135));
  NR2B1M2R g10832__7410(.B (n_154), .NA (n_187), .Z (n_134));
  AO22B10M2R g10833__6417(.A1 (n_274), .B1 (n_326), .B2 (n_8), .NA2
       (n_368), .Z (n_133));
  NR2B1M2R g10834__5477(.B (controller_state[3]), .NA
       (controller_state[0]), .Z (n_132));
  DFQZRM2RA \BURST_counter_reg[0] (.CK (clk), .D (n_49), .RB (n_9), .Q
       (BURST_counter[0]));
  DFQZRM2RA \BURST_counter_reg[1] (.CK (clk), .D (n_65), .RB (n_9), .Q
       (BURST_counter[1]));
  DFQZSM2RA \BURST_counter_reg[2] (.CK (clk), .D (n_69), .SB (n_9), .Q
       (BURST_counter[2]));
  DFQM2RA \CAS_counter_reg[0] (.CK (clk), .D (n_75), .Q
       (CAS_counter[0]));
  DFQM2RA \CAS_counter_reg[1] (.CK (clk), .D (n_107), .Q
       (CAS_counter[1]));
  DFQZRM2RA \CAS_counter_reg[2] (.CK (clk), .D (n_96), .RB (n_9), .Q
       (CAS_counter[2]));
  DFQM2RA \CAS_counter_reg[3] (.CK (clk), .D (n_108), .Q
       (CAS_counter[3]));
  DFQM2RA \PRE_counter_reg[0] (.CK (clk), .D (n_88), .Q
       (PRE_counter[0]));
  DFQZSM2RA \PRE_counter_reg[1] (.CK (clk), .D (n_93), .SB (n_9), .Q
       (PRE_counter[1]));
  DFQZRM2RA \PRE_counter_reg[2] (.CK (clk), .D (n_85), .RB (n_9), .Q
       (PRE_counter[2]));
  DFQZRM2RA \RCD_counter_reg[0] (.CK (clk), .D (n_35), .RB (n_9), .Q
       (RCD_counter[0]));
  DFQM2RA \RCD_counter_reg[1] (.CK (clk), .D (n_86), .Q
       (RCD_counter[1]));
  DFQM2RA \RCD_counter_reg[2] (.CK (clk), .D (n_83), .Q
       (RCD_counter[2]));
  DFQZSM2RA \RCD_counter_reg[3] (.CK (clk), .D (n_63), .SB (n_9), .Q
       (RCD_counter[3]));
  SDFQM2RA \REF_counter_reg[0] (.CK (clk), .D (n_60), .SD (n_20), .SE
       (REF_counter[0]), .Q (REF_counter[0]));
  DFQM2RA \REF_counter_reg[1] (.CK (clk), .D (n_97), .Q
       (REF_counter[1]));
  DFQM2RA \REF_counter_reg[2] (.CK (clk), .D (n_112), .Q
       (REF_counter[2]));
  DFQM2RA \REF_counter_reg[3] (.CK (clk), .D (n_102), .Q
       (REF_counter[3]));
  SDFQM2RA \REF_counter_reg[4] (.CK (clk), .D (n_80), .SD (n_67), .SE
       (REF_counter[4]), .Q (REF_counter[4]));
  DFQM2RA \REF_counter_reg[5] (.CK (clk), .D (n_94), .Q
       (REF_counter[5]));
  DFQZSM2RA \REF_counter_reg[6] (.CK (clk), .D (n_64), .SB (n_50), .Q
       (REF_counter[6]));
  DFQM2RA \REF_counter_reg[7] (.CK (clk), .D (n_101), .Q
       (REF_counter[7]));
  SDFQM2RA \REF_counter_reg[8] (.CK (clk), .D (n_79), .SD (n_77), .SE
       (REF_counter[8]), .Q (REF_counter[8]));
  DFQZRM1RA \bank_id_reg[0] (.CK (clk), .D (n_45), .RB (n_9), .Q
       (bank_id[0]));
  DFQZRM1RA \bank_id_reg[1] (.CK (clk), .D (n_41), .RB (n_9), .Q
       (bank_id[1]));
  DFQZRM1RA cmd_exec_ack_reg238(.CK (clk), .D (n_14), .RB (n_9), .Q
       (cmd_exec_ack));
  DFQZRM1RA \column_addr_reg[0] (.CK (clk), .D (n_40), .RB (n_9), .Q
       (column_addr[0]));
  DFQZRM1RA \column_addr_reg[1] (.CK (clk), .D (n_43), .RB (n_9), .Q
       (column_addr[1]));
  DFQZRM1RA \column_addr_reg[2] (.CK (clk), .D (n_39), .RB (n_9), .Q
       (column_addr[2]));
  DFQZRM2RA \controller_state_reg[0] (.CK (clk), .D
       (next_controller_state[0]), .RB (n_9), .Q (controller_state[0]));
  DFEQZRM1RA \data_counter_reg[2] (.CK (clk), .D (n_95), .E (n_70), .RB
       (n_9), .Q (data_counter[2]));
  DFEQZRM1RA \data_counter_reg[3] (.CK (clk), .D (n_113), .E (n_70),
       .RB (n_9), .Q (data_counter[3]));
  DFQZRM2RA \refresh_counter_reg[1] (.CK (clk), .D (n_54), .RB (n_124),
       .Q (refresh_counter[1]));
  DFQZSM2RA \refresh_counter_reg[2] (.CK (clk), .D (n_121), .SB
       (n_129), .Q (refresh_counter[2]));
  DFQZRM2RA \refresh_counter_reg[3] (.CK (clk), .D (n_53), .RB (n_124),
       .Q (refresh_counter[3]));
  DFQZSM2RA \refresh_counter_reg[4] (.CK (clk), .D (n_120), .SB
       (n_129), .Q (refresh_counter[4]));
  DFQZRM2RA \refresh_counter_reg[5] (.CK (clk), .D (n_52), .RB (n_124),
       .Q (refresh_counter[5]));
  DFQZSM2RA \refresh_counter_reg[6] (.CK (clk), .D (n_123), .SB
       (n_129), .Q (refresh_counter[6]));
  DFQZSM2RA \refresh_counter_reg[7] (.CK (clk), .D (n_118), .SB
       (n_129), .Q (refresh_counter[7]));
  DFQZRM2RA \refresh_counter_reg[8] (.CK (clk), .D (n_51), .RB (n_124),
       .Q (refresh_counter[8]));
  DFQZRM2RA \refresh_counter_reg[9] (.CK (clk), .D (n_55), .RB (n_124),
       .Q (refresh_counter[9]));
  DFQZRM2RA \refresh_counter_reg[10] (.CK (clk), .D (n_57), .RB
       (n_124), .Q (refresh_counter[10]));
  DFQZRM2RA \refresh_counter_reg[11] (.CK (clk), .D (n_58), .RB
       (n_124), .Q (refresh_counter[11]));
  DFQZSM2RA \refresh_counter_reg[12] (.CK (clk), .D (n_117), .SB
       (n_129), .Q (refresh_counter[12]));
  DFQM2RA \refresh_counter_reg[13] (.CK (clk), .D (n_131), .Q
       (refresh_counter[13]));
  DFQZRM1RA \row_addr_reg[0] (.CK (clk), .D (n_38), .RB (n_9), .Q
       (row_addr[0]));
  DFQZRM1RA \row_addr_reg[1] (.CK (clk), .D (n_37), .RB (n_9), .Q
       (row_addr[1]));
  DFQZRM1RA \row_addr_reg[2] (.CK (clk), .D (n_36), .RB (n_9), .Q
       (row_addr[2]));
  DFQZRM1RA \row_addr_reg[3] (.CK (clk), .D (n_42), .RB (n_9), .Q
       (row_addr[3]));
  DFQZRM1RA \row_addr_reg[4] (.CK (clk), .D (n_44), .RB (n_9), .Q
       (row_addr[4]));
  DFQZRM1RA \row_addr_reg[5] (.CK (clk), .D (n_46), .RB (n_9), .Q
       (row_addr[5]));
  SDFQM2RA temp_cmd_reg(.CK (clk), .D (temp_cmd), .SD (WR_command), .SE
       (n_11), .Q (temp_cmd));
  SDFQM2RA \temp_write_data_reg[0][0] (.CK (clk), .D (Write_data[0]),
       .SD (\temp_write_data[0] [0]), .SE (n_127), .Q
       (\temp_write_data[0] [0]));
  SDFQM2RA \temp_write_data_reg[0][1] (.CK (clk), .D (Write_data[1]),
       .SD (\temp_write_data[0] [1]), .SE (n_127), .Q
       (\temp_write_data[0] [1]));
  SDFQM2RA \temp_write_data_reg[0][2] (.CK (clk), .D (Write_data[2]),
       .SD (\temp_write_data[0] [2]), .SE (n_127), .Q
       (\temp_write_data[0] [2]));
  SDFQM2RA \temp_write_data_reg[0][3] (.CK (clk), .D (Write_data[3]),
       .SD (\temp_write_data[0] [3]), .SE (n_127), .Q
       (\temp_write_data[0] [3]));
  SDFQM2RA \temp_write_data_reg[0][4] (.CK (clk), .D (Write_data[4]),
       .SD (\temp_write_data[0] [4]), .SE (n_127), .Q
       (\temp_write_data[0] [4]));
  SDFQM2RA \temp_write_data_reg[0][5] (.CK (clk), .D (Write_data[5]),
       .SD (\temp_write_data[0] [5]), .SE (n_127), .Q
       (\temp_write_data[0] [5]));
  SDFQM2RA \temp_write_data_reg[0][6] (.CK (clk), .D (Write_data[6]),
       .SD (\temp_write_data[0] [6]), .SE (n_127), .Q
       (\temp_write_data[0] [6]));
  SDFQM2RA \temp_write_data_reg[0][7] (.CK (clk), .D (Write_data[7]),
       .SD (\temp_write_data[0] [7]), .SE (n_127), .Q
       (\temp_write_data[0] [7]));
  SDFQM2RA \temp_write_data_reg[0][8] (.CK (clk), .D (Write_data[8]),
       .SD (\temp_write_data[0] [8]), .SE (n_127), .Q
       (\temp_write_data[0] [8]));
  SDFQM2RA \temp_write_data_reg[0][9] (.CK (clk), .D (Write_data[9]),
       .SD (\temp_write_data[0] [9]), .SE (n_127), .Q
       (\temp_write_data[0] [9]));
  SDFQM2RA \temp_write_data_reg[0][10] (.CK (clk), .D (Write_data[10]),
       .SD (\temp_write_data[0] [10]), .SE (n_127), .Q
       (\temp_write_data[0] [10]));
  SDFQM2RA \temp_write_data_reg[0][11] (.CK (clk), .D (Write_data[11]),
       .SD (\temp_write_data[0] [11]), .SE (n_127), .Q
       (\temp_write_data[0] [11]));
  SDFQM2RA \temp_write_data_reg[0][12] (.CK (clk), .D (Write_data[12]),
       .SD (\temp_write_data[0] [12]), .SE (n_127), .Q
       (\temp_write_data[0] [12]));
  SDFQM2RA \temp_write_data_reg[0][13] (.CK (clk), .D (Write_data[13]),
       .SD (\temp_write_data[0] [13]), .SE (n_127), .Q
       (\temp_write_data[0] [13]));
  SDFQM2RA \temp_write_data_reg[0][14] (.CK (clk), .D (Write_data[14]),
       .SD (\temp_write_data[0] [14]), .SE (n_127), .Q
       (\temp_write_data[0] [14]));
  SDFQM2RA \temp_write_data_reg[0][15] (.CK (clk), .D (Write_data[15]),
       .SD (\temp_write_data[0] [15]), .SE (n_127), .Q
       (\temp_write_data[0] [15]));
  SDFQM2RA \temp_write_data_reg[1][0] (.CK (clk), .D (Write_data[0]),
       .SD (\temp_write_data[1] [0]), .SE (n_130), .Q
       (\temp_write_data[1] [0]));
  SDFQM2RA \temp_write_data_reg[1][1] (.CK (clk), .D (Write_data[1]),
       .SD (\temp_write_data[1] [1]), .SE (n_130), .Q
       (\temp_write_data[1] [1]));
  SDFQM2RA \temp_write_data_reg[1][2] (.CK (clk), .D (Write_data[2]),
       .SD (\temp_write_data[1] [2]), .SE (n_130), .Q
       (\temp_write_data[1] [2]));
  SDFQM2RA \temp_write_data_reg[1][3] (.CK (clk), .D (Write_data[3]),
       .SD (\temp_write_data[1] [3]), .SE (n_130), .Q
       (\temp_write_data[1] [3]));
  SDFQM2RA \temp_write_data_reg[1][4] (.CK (clk), .D (Write_data[4]),
       .SD (\temp_write_data[1] [4]), .SE (n_130), .Q
       (\temp_write_data[1] [4]));
  SDFQM2RA \temp_write_data_reg[1][5] (.CK (clk), .D (Write_data[5]),
       .SD (\temp_write_data[1] [5]), .SE (n_130), .Q
       (\temp_write_data[1] [5]));
  SDFQM2RA \temp_write_data_reg[1][6] (.CK (clk), .D (Write_data[6]),
       .SD (\temp_write_data[1] [6]), .SE (n_130), .Q
       (\temp_write_data[1] [6]));
  SDFQM2RA \temp_write_data_reg[1][7] (.CK (clk), .D (Write_data[7]),
       .SD (\temp_write_data[1] [7]), .SE (n_130), .Q
       (\temp_write_data[1] [7]));
  SDFQM2RA \temp_write_data_reg[1][8] (.CK (clk), .D (Write_data[8]),
       .SD (\temp_write_data[1] [8]), .SE (n_130), .Q
       (\temp_write_data[1] [8]));
  SDFQM2RA \temp_write_data_reg[1][9] (.CK (clk), .D (Write_data[9]),
       .SD (\temp_write_data[1] [9]), .SE (n_130), .Q
       (\temp_write_data[1] [9]));
  SDFQM2RA \temp_write_data_reg[1][10] (.CK (clk), .D (Write_data[10]),
       .SD (\temp_write_data[1] [10]), .SE (n_130), .Q
       (\temp_write_data[1] [10]));
  SDFQM2RA \temp_write_data_reg[1][11] (.CK (clk), .D (Write_data[11]),
       .SD (\temp_write_data[1] [11]), .SE (n_130), .Q
       (\temp_write_data[1] [11]));
  SDFQM2RA \temp_write_data_reg[1][12] (.CK (clk), .D (Write_data[12]),
       .SD (\temp_write_data[1] [12]), .SE (n_130), .Q
       (\temp_write_data[1] [12]));
  SDFQM2RA \temp_write_data_reg[1][13] (.CK (clk), .D (Write_data[13]),
       .SD (\temp_write_data[1] [13]), .SE (n_130), .Q
       (\temp_write_data[1] [13]));
  SDFQM2RA \temp_write_data_reg[1][14] (.CK (clk), .D (Write_data[14]),
       .SD (\temp_write_data[1] [14]), .SE (n_130), .Q
       (\temp_write_data[1] [14]));
  SDFQM2RA \temp_write_data_reg[1][15] (.CK (clk), .D (Write_data[15]),
       .SD (\temp_write_data[1] [15]), .SE (n_130), .Q
       (\temp_write_data[1] [15]));
  SDFQM2RA \temp_write_data_reg[2][0] (.CK (clk), .D
       (\temp_write_data[2] [0]), .SD (Write_data[0]), .SE (n_128), .Q
       (\temp_write_data[2] [0]));
  SDFQM2RA \temp_write_data_reg[2][1] (.CK (clk), .D
       (\temp_write_data[2] [1]), .SD (Write_data[1]), .SE (n_128), .Q
       (\temp_write_data[2] [1]));
  SDFQM2RA \temp_write_data_reg[2][2] (.CK (clk), .D
       (\temp_write_data[2] [2]), .SD (Write_data[2]), .SE (n_128), .Q
       (\temp_write_data[2] [2]));
  SDFQM2RA \temp_write_data_reg[2][3] (.CK (clk), .D
       (\temp_write_data[2] [3]), .SD (Write_data[3]), .SE (n_128), .Q
       (\temp_write_data[2] [3]));
  SDFQM2RA \temp_write_data_reg[2][4] (.CK (clk), .D
       (\temp_write_data[2] [4]), .SD (Write_data[4]), .SE (n_128), .Q
       (\temp_write_data[2] [4]));
  SDFQM2RA \temp_write_data_reg[2][5] (.CK (clk), .D
       (\temp_write_data[2] [5]), .SD (Write_data[5]), .SE (n_128), .Q
       (\temp_write_data[2] [5]));
  SDFQM2RA \temp_write_data_reg[2][6] (.CK (clk), .D
       (\temp_write_data[2] [6]), .SD (Write_data[6]), .SE (n_128), .Q
       (\temp_write_data[2] [6]));
  SDFQM2RA \temp_write_data_reg[2][7] (.CK (clk), .D
       (\temp_write_data[2] [7]), .SD (Write_data[7]), .SE (n_128), .Q
       (\temp_write_data[2] [7]));
  SDFQM2RA \temp_write_data_reg[2][8] (.CK (clk), .D
       (\temp_write_data[2] [8]), .SD (Write_data[8]), .SE (n_128), .Q
       (\temp_write_data[2] [8]));
  SDFQM2RA \temp_write_data_reg[2][9] (.CK (clk), .D
       (\temp_write_data[2] [9]), .SD (Write_data[9]), .SE (n_128), .Q
       (\temp_write_data[2] [9]));
  SDFQM2RA \temp_write_data_reg[2][10] (.CK (clk), .D
       (\temp_write_data[2] [10]), .SD (Write_data[10]), .SE (n_128),
       .Q (\temp_write_data[2] [10]));
  SDFQM2RA \temp_write_data_reg[2][11] (.CK (clk), .D
       (\temp_write_data[2] [11]), .SD (Write_data[11]), .SE (n_128),
       .Q (\temp_write_data[2] [11]));
  SDFQM2RA \temp_write_data_reg[2][12] (.CK (clk), .D
       (\temp_write_data[2] [12]), .SD (Write_data[12]), .SE (n_128),
       .Q (\temp_write_data[2] [12]));
  SDFQM2RA \temp_write_data_reg[2][13] (.CK (clk), .D
       (\temp_write_data[2] [13]), .SD (Write_data[13]), .SE (n_128),
       .Q (\temp_write_data[2] [13]));
  SDFQM2RA \temp_write_data_reg[2][14] (.CK (clk), .D
       (\temp_write_data[2] [14]), .SD (Write_data[14]), .SE (n_128),
       .Q (\temp_write_data[2] [14]));
  SDFQM2RA \temp_write_data_reg[2][15] (.CK (clk), .D
       (\temp_write_data[2] [15]), .SD (Write_data[15]), .SE (n_128),
       .Q (\temp_write_data[2] [15]));
  SDFQM2RA \temp_write_data_reg[3][0] (.CK (clk), .D
       (\temp_write_data[3] [0]), .SD (Write_data[0]), .SE (n_125), .Q
       (\temp_write_data[3] [0]));
  SDFQM2RA \temp_write_data_reg[3][1] (.CK (clk), .D
       (\temp_write_data[3] [1]), .SD (Write_data[1]), .SE (n_125), .Q
       (\temp_write_data[3] [1]));
  SDFQM2RA \temp_write_data_reg[3][2] (.CK (clk), .D
       (\temp_write_data[3] [2]), .SD (Write_data[2]), .SE (n_125), .Q
       (\temp_write_data[3] [2]));
  SDFQM2RA \temp_write_data_reg[3][3] (.CK (clk), .D
       (\temp_write_data[3] [3]), .SD (Write_data[3]), .SE (n_125), .Q
       (\temp_write_data[3] [3]));
  SDFQM2RA \temp_write_data_reg[3][4] (.CK (clk), .D
       (\temp_write_data[3] [4]), .SD (Write_data[4]), .SE (n_125), .Q
       (\temp_write_data[3] [4]));
  SDFQM2RA \temp_write_data_reg[3][5] (.CK (clk), .D
       (\temp_write_data[3] [5]), .SD (Write_data[5]), .SE (n_125), .Q
       (\temp_write_data[3] [5]));
  SDFQM2RA \temp_write_data_reg[3][6] (.CK (clk), .D
       (\temp_write_data[3] [6]), .SD (Write_data[6]), .SE (n_125), .Q
       (\temp_write_data[3] [6]));
  SDFQM2RA \temp_write_data_reg[3][7] (.CK (clk), .D
       (\temp_write_data[3] [7]), .SD (Write_data[7]), .SE (n_125), .Q
       (\temp_write_data[3] [7]));
  SDFQM2RA \temp_write_data_reg[3][8] (.CK (clk), .D
       (\temp_write_data[3] [8]), .SD (Write_data[8]), .SE (n_125), .Q
       (\temp_write_data[3] [8]));
  SDFQM2RA \temp_write_data_reg[3][9] (.CK (clk), .D
       (\temp_write_data[3] [9]), .SD (Write_data[9]), .SE (n_125), .Q
       (\temp_write_data[3] [9]));
  SDFQM2RA \temp_write_data_reg[3][10] (.CK (clk), .D
       (\temp_write_data[3] [10]), .SD (Write_data[10]), .SE (n_125),
       .Q (\temp_write_data[3] [10]));
  SDFQM2RA \temp_write_data_reg[3][11] (.CK (clk), .D
       (\temp_write_data[3] [11]), .SD (Write_data[11]), .SE (n_125),
       .Q (\temp_write_data[3] [11]));
  SDFQM2RA \temp_write_data_reg[3][12] (.CK (clk), .D
       (\temp_write_data[3] [12]), .SD (Write_data[12]), .SE (n_125),
       .Q (\temp_write_data[3] [12]));
  SDFQM2RA \temp_write_data_reg[3][13] (.CK (clk), .D
       (\temp_write_data[3] [13]), .SD (Write_data[13]), .SE (n_125),
       .Q (\temp_write_data[3] [13]));
  SDFQM2RA \temp_write_data_reg[3][14] (.CK (clk), .D
       (\temp_write_data[3] [14]), .SD (Write_data[14]), .SE (n_125),
       .Q (\temp_write_data[3] [14]));
  SDFQM2RA \temp_write_data_reg[3][15] (.CK (clk), .D
       (\temp_write_data[3] [15]), .SD (Write_data[15]), .SE (n_125),
       .Q (\temp_write_data[3] [15]));
  SDFQZRM1RA \write_burst_count_reg[1] (.CK (clk), .D (n_89), .RB
       (n_369), .SD (n_99), .SE (write_burst_count[1]), .Q
       (write_burst_count[1]));
  SDFQZRM1RA \write_burst_count_reg[3] (.CK (clk), .D (n_89), .RB
       (n_61), .SD (n_98), .SE (write_burst_count[3]), .Q
       (write_burst_count[3]));
  DFQM2RA \write_burst_count_reg[5] (.CK (clk), .D (n_122), .Q
       (write_burst_count[5]));
  OAI21B20M2R g9494__2398(.B (n_129), .NA1 (refresh_counter[13]), .NA2
       (n_301), .Z (n_131));
  ND2M2R g9500__5107(.A (data_counter[0]), .B (n_126), .Z (n_130));
  OA21M2RA g9501__6260(.A1 (n_114), .A2 (n_330), .B (n_9), .Z (n_129));
  NR2M2R g9502__4319(.A (n_119), .B (data_counter[0]), .Z (n_128));
  ND2M2R g9503__8428(.A (n_3), .B (n_126), .Z (n_127));
  NR2M2R g9504__5526(.A (n_116), .B (data_counter[1]), .Z (n_126));
  NR2M2R g9510__6783(.A (n_116), .B (n_29), .Z (n_125));
  AOI21M2R g9511__3680(.A1 (n_306), .A2 (n_16), .B (n_115), .Z (n_123));
  AO32M2RA g9512__1617(.A1 (n_87), .A2 (write_burst_count[4]), .A3
       (n_89), .B1 (write_burst_count[5]), .B2 (n_109), .Z (n_122));
  AOI21M2R g9513__2802(.A1 (n_322), .A2 (n_12), .B (n_115), .Z (n_121));
  AOI21M2R g9514__1705(.A1 (n_307), .A2 (n_25), .B (n_115), .Z (n_120));
  ND2B1M2R g9515__5122(.B (data_counter[1]), .NA (n_116), .Z (n_119));
  AOI21M2R g9516__8246(.A1 (n_305), .A2 (n_15), .B (n_115), .Z (n_118));
  AOI21M2R g9517__7098(.A1 (n_301), .A2 (n_19), .B (n_115), .Z (n_117));
  NR2M2R g9518__6131(.A (reset), .B (n_115), .Z (n_124));
  INVM2R g9524(.A (n_115), .Z (n_114));
  AO21M2RA g9525__1881(.A1 (n_81), .A2 (data_counter[2]), .B
       (data_counter[3]), .Z (n_113));
  OAI211M2R g9526__5115(.A1 (REF_counter[2]), .A2 (n_62), .B (n_106),
       .C (n_50), .Z (n_112));
  OAI32M2R g9527__7482(.A1 (n_90), .A2 (write_burst_count[4]), .A3
       (n_78), .B1 (n_105), .B2 (n_4), .Z (n_111));
  OAI32M2R g9528__4733(.A1 (n_90), .A2 (n_31), .A3
       (write_burst_count[2]), .B1 (n_103), .B2 (n_5), .Z (n_110));
  ND4B1M2R g9529__6161(.B (n_0), .C (temp_cmd), .D (n_9), .NA
       (data_counter[2]), .Z (n_116));
  NR3M2R g9530__9315(.A (refresh_counter[8]), .B (n_104), .C (n_306),
       .Z (n_115));
  OAI21M2R g9536__9945(.A1 (n_72), .A2 (write_burst_count[4]), .B
       (n_105), .Z (n_109));
  AO211M1RA g9541__2883(.A1 (n_324), .A2 (CAS_counter[3]), .B (n_73),
       .C (reset), .Z (n_108));
  AO211M1RA g9542__2346(.A1 (n_324), .A2 (CAS_counter[1]), .B (n_74),
       .C (reset), .Z (n_107));
  ND2M1R g9543__1666(.A (n_62), .B (REF_counter[2]), .Z (n_106));
  OR6M1RA g9553__7410(.A (refresh_counter[7]), .B
       (refresh_counter[12]), .C (refresh_counter[9]), .D
       (refresh_counter[13]), .E (refresh_counter[11]), .F
       (refresh_counter[10]), .Z (n_104));
  AOI21M2R g9554__6417(.A1 (n_31), .A2 (n_71), .B (n_92), .Z (n_103));
  AO21M2RA g9555__5477(.A1 (REF_counter[3]), .A2 (n_68), .B (n_80), .Z
       (n_102));
  AO21M2RA g9556__2398(.A1 (REF_counter[7]), .A2 (n_66), .B (n_79), .Z
       (n_101));
  OAI21M2R g9557__5107(.A1 (n_1), .A2 (n_70), .B (n_82), .Z (n_100));
  OAI21M2R g9558__6260(.A1 (n_72), .A2 (n_369), .B (n_91), .Z (n_99));
  OAI21M1R g9559__4319(.A1 (n_72), .A2 (n_61), .B (n_91), .Z (n_98));
  OAI211B100M2R g9560__8428(.A1 (n_34), .B (n_62), .C (n_50), .NA2
       (REF_counter[1]), .Z (n_97));
  AO32M2RA g9561__5526(.A1 (n_326), .A2 (n_56), .A3 (n_8), .B1 (n_324),
       .B2 (CAS_counter[2]), .Z (n_96));
  MXB2M1RA g9562__6783(.A (n_29), .B (n_81), .S (data_counter[2]), .Z
       (n_95));
  AO22B10M2R g9563__3680(.A1 (n_60), .B1 (REF_counter[5]), .B2 (n_76),
       .NA2 (n_296), .Z (n_94));
  XOR2M2RA g9564__1617(.A (n_30), .B (PRE_counter[1]), .Z (n_93));
  AOI21M2R g9565__2802(.A1 (n_78), .A2 (n_71), .B (n_92), .Z (n_105));
  INVM2R g9578(.A (n_92), .Z (n_91));
  INVM2R g9579(.A (n_90), .Z (n_89));
  AO211M2RA g9580__1705(.A1 (n_300), .A2 (PRE_counter[0]), .B (n_30),
       .C (reset), .Z (n_88));
  NR2M2R g9582__5122(.A (write_burst_count[5]), .B (n_78), .Z (n_87));
  OAI22M2R g9583__8246(.A1 (n_28), .A2 (n_47), .B1 (reset), .B2 (n_26),
       .Z (n_86));
  AO22M1RA g9584__7098(.A1 (n_302), .A2 (n_59), .B1 (n_300), .B2
       (PRE_counter[2]), .Z (n_85));
  OAI221M2R g9585__6131(.A1 (n_2), .A2 (n_33), .B1 (n_302), .B2
       (n_300), .C (n_9), .Z (n_84));
  AO211M2RA g9586__1881(.A1 (n_22), .A2 (RCD_counter[2]), .B (n_32), .C
       (reset), .Z (n_83));
  OAI211M2R g9587__5115(.A1 (data_counter[0]), .A2 (data_counter[1]),
       .B (n_70), .C (n_29), .Z (n_82));
  NR2M2R g9590__7482(.A (n_72), .B (temp_cmd), .Z (n_92));
  ND2M2R g9592__4733(.A (temp_cmd), .B (n_71), .Z (n_90));
  INVM2R g9593(.A (n_29), .Z (n_81));
  AO21M2RA g9594__6161(.A1 (n_314), .A2 (n_27), .B (n_20), .Z (n_77));
  AO21M2RA g9596__9315(.A1 (n_312), .A2 (n_27), .B (n_20), .Z (n_76));
  OAI211M2R g9597__9945(.A1 (CAS_counter[0]), .A2 (n_324), .B (n_18),
       .C (n_9), .Z (n_75));
  AOI21M2R g9598__2883(.A1 (n_17), .A2 (n_316), .B (n_324), .Z (n_74));
  AOI21M2R g9599__2346(.A1 (n_326), .A2 (n_13), .B (n_324), .Z (n_73));
  NR2B1M2R g9600__1666(.B (n_315), .NA (n_60), .Z (n_80));
  NR2B1M2R g9601__7410(.B (n_314), .NA (n_60), .Z (n_79));
  ND2M2R g9602__6417(.A (n_61), .B (write_burst_count[3]), .Z (n_78));
  INVM2R g9603(.A (n_72), .Z (n_71));
  XOR2M2RA g9605__5477(.A (n_23), .B (BURST_counter[2]), .Z (n_69));
  AO21M2RA g9606__2398(.A1 (n_313), .A2 (n_27), .B (n_20), .Z (n_68));
  AO21M2RA g9607__5107(.A1 (n_315), .A2 (n_27), .B (n_20), .Z (n_67));
  AO21M2RA g9608__6260(.A1 (n_311), .A2 (n_27), .B (n_20), .Z (n_66));
  OAI21M2R g9609__4319(.A1 (n_295), .A2 (n_323), .B (n_48), .Z (n_65));
  XOR2M2RA g9610__8428(.A (n_24), .B (REF_counter[6]), .Z (n_64));
  XOR2M2RA g9611__5526(.A (n_32), .B (RCD_counter[3]), .Z (n_63));
  ND4B1M2R g9612__6783(.B (controller_state[0]), .C
       (controller_state[3]), .D (n_9), .NA (n_339), .Z (n_72));
  AOI32M2R g9613__3680(.A1 (data_counter[3]), .A2 (data_counter[2]),
       .A3 (data_counter[1]), .B1 (n_294), .B2 (n_363), .Z (n_70));
  AO21M2RA g9614__1617(.A1 (n_309), .A2 (PRE_counter[2]), .B (n_33), .Z
       (n_59));
  OAI21B20M2R g9617__2802(.B (n_304), .NA1 (refresh_counter[11]), .NA2
       (n_299), .Z (n_58));
  OAI21B20M2R g9618__1705(.B (n_299), .NA1 (refresh_counter[10]), .NA2
       (n_319), .Z (n_57));
  OAI21B20M2R g9619__5122(.B (n_317), .NA1 (CAS_counter[2]), .NA2
       (n_316), .Z (n_56));
  OAI21B20M2R g9620__8246(.B (n_319), .NA1 (refresh_counter[9]), .NA2
       (n_320), .Z (n_55));
  OAI21B20M2R g9621__7098(.B (n_318), .NA1 (refresh_counter[1]), .NA2
       (refresh_counter[0]), .Z (n_54));
  OAI21B20M2R g9622__6131(.B (n_308), .NA1 (refresh_counter[3]), .NA2
       (n_322), .Z (n_53));
  OAI21B20M2R g9623__1881(.B (n_321), .NA1 (refresh_counter[5]), .NA2
       (n_307), .Z (n_52));
  OAI21B20M2R g9624__5115(.B (n_320), .NA1 (refresh_counter[8]), .NA2
       (n_305), .Z (n_51));
  ND2B1M2R g9627__7482(.B (n_34), .NA (REF_counter[1]), .Z (n_62));
  NR2M2R g9628__4733(.A (n_31), .B (n_5), .Z (n_61));
  NR2M2R g9629__6161(.A (n_28), .B (n_365), .Z (n_60));
  MOAI22M2RA g9630__9315(.A1 (n_323), .A2 (BURST_counter[0]), .B1
       (n_367), .B2 (BURST_counter[0]), .Z (n_49));
  OAI21M2R g9631__9945(.A1 (BURST_counter[0]), .A2 (n_367), .B
       (BURST_counter[1]), .Z (n_48));
  AOI21M2R g9632__2883(.A1 (RCD_counter[1]), .A2 (RCD_counter[0]), .B
       (n_21), .Z (n_47));
  AO22M1RA g9633__2346(.A1 (DRAM_Address[8]), .A2 (n_7), .B1 (n_368),
       .B2 (row_addr[5]), .Z (n_46));
  AO22M1RA g9634__1666(.A1 (DRAM_Address[9]), .A2 (n_7), .B1 (n_368),
       .B2 (bank_id[0]), .Z (n_45));
  AO22M1RA g9635__7410(.A1 (DRAM_Address[7]), .A2 (n_7), .B1 (n_368),
       .B2 (row_addr[4]), .Z (n_44));
  AO22M1RA g9636__6417(.A1 (DRAM_Address[1]), .A2 (n_7), .B1 (n_368),
       .B2 (column_addr[1]), .Z (n_43));
  AO22M1RA g9637__5477(.A1 (DRAM_Address[6]), .A2 (n_7), .B1 (n_368),
       .B2 (row_addr[3]), .Z (n_42));
  AO22M1RA g9638__2398(.A1 (DRAM_Address[10]), .A2 (n_7), .B1 (n_368),
       .B2 (bank_id[1]), .Z (n_41));
  AO22M1RA g9639__5107(.A1 (DRAM_Address[0]), .A2 (n_7), .B1 (n_368),
       .B2 (column_addr[0]), .Z (n_40));
  AO22M1RA g9640__6260(.A1 (DRAM_Address[2]), .A2 (n_7), .B1 (n_368),
       .B2 (column_addr[2]), .Z (n_39));
  AO22M1RA g9641__4319(.A1 (DRAM_Address[3]), .A2 (n_7), .B1 (n_368),
       .B2 (row_addr[0]), .Z (n_38));
  AO22M1RA g9642__8428(.A1 (DRAM_Address[4]), .A2 (n_7), .B1 (n_368),
       .B2 (row_addr[1]), .Z (n_37));
  AO22M1RA g9643__5526(.A1 (DRAM_Address[5]), .A2 (n_7), .B1 (n_368),
       .B2 (row_addr[2]), .Z (n_36));
  MOAI22M2RA g9644__6783(.A1 (n_325), .A2 (RCD_counter[0]), .B1
       (n_363), .B2 (RCD_counter[0]), .Z (n_35));
  OA21M2RA g9645__3680(.A1 (n_365), .A2 (n_366), .B (n_9), .Z (n_50));
  INVM2R g9646(.A (n_28), .Z (n_27));
  ND2M2R g9647__1617(.A (n_363), .B (RCD_counter[1]), .Z (n_26));
  CKND2M2R g9648__2802(.A (n_308), .B (refresh_counter[4]), .Z (n_25));
  NR2M2R g9649__1705(.A (REF_counter[0]), .B (n_365), .Z (n_34));
  NR2M2R g9650__5122(.A (n_365), .B (n_296), .Z (n_24));
  NR2M2R g9651__8246(.A (n_298), .B (n_300), .Z (n_33));
  NR2M2R g9652__7098(.A (n_295), .B (n_367), .Z (n_23));
  NR2M2R g9653__6131(.A (n_310), .B (n_363), .Z (n_32));
  ND2M2R g9654__1881(.A (write_burst_count[1]), .B (n_369), .Z (n_31));
  NR2M2R g9655__5115(.A (PRE_counter[0]), .B (n_300), .Z (n_30));
  ND2M2R g9656__7482(.A (data_counter[1]), .B (data_counter[0]), .Z
       (n_29));
  ND2M2R g9657__4733(.A (n_366), .B (n_9), .Z (n_28));
  INVM2R g9658(.A (n_21), .Z (n_22));
  CKND2M2R g9659__6161(.A (n_304), .B (refresh_counter[12]), .Z (n_19));
  ND2M2R g9660__9315(.A (n_324), .B (CAS_counter[0]), .Z (n_18));
  CKND2M2R g9661__9945(.A (CAS_counter[0]), .B (CAS_counter[1]), .Z
       (n_17));
  CKND2M2R g9662__2883(.A (n_321), .B (refresh_counter[6]), .Z (n_16));
  CKND2M2R g9663__2346(.A (n_306), .B (refresh_counter[7]), .Z (n_15));
  CKND2M2R g9664__1666(.A (n_368), .B (n_9), .Z (n_14));
  CKND2M2R g9665__7410(.A (n_317), .B (CAS_counter[3]), .Z (n_13));
  ND2M2R g9666__6417(.A (n_318), .B (refresh_counter[2]), .Z (n_12));
  NR2M2R g9667__5477(.A (reset), .B (n_368), .Z (n_11));
  NR2M2R g9668__2398(.A (n_297), .B (n_363), .Z (n_21));
  NR2M2R g9669__5107(.A (reset), .B (n_10), .Z (n_20));
  INVM2R g9681(.A (n_365), .Z (n_10));
  INVM2R g9691(.A (reset), .Z (n_9));
  INVM2R g9698(.A (n_368), .Z (n_7));
  DFM2RA \PRE_counter_reg[3] (.CK (clk), .D (n_84), .Q
       (PRE_counter[3]), .QB (n_2));
  DFEZRM2RA \data_counter_reg[0] (.CK (clk), .D (n_3), .E (n_70), .RB
       (n_9), .Q (data_counter[0]), .QB (n_3));
  DFZRM2RA \data_counter_reg[1] (.CK (clk), .D (n_100), .RB (n_9), .Q
       (data_counter[1]), .QB (n_1));
  DFZRM2RA \refresh_counter_reg[0] (.CK (clk), .D (n_6), .RB (n_124),
       .Q (refresh_counter[0]), .QB (n_6));
  DFM2RA \write_burst_count_reg[2] (.CK (clk), .D (n_110), .Q
       (write_burst_count[2]), .QB (n_5));
  DFM2RA \write_burst_count_reg[4] (.CK (clk), .D (n_111), .Q
       (write_burst_count[4]), .QB (n_4));
  NR2B1M1R g10835__6260(.B (data_counter[3]), .NA (n_70), .Z (n_0));
  DFZRM2RA \controller_state_reg[1] (.CK (clk), .D
       (next_controller_state[1]), .RB (n_9), .Q (controller_state[1]),
       .QB (n_140));
  DFZRM2RA \controller_state_reg[3] (.CK (clk), .D
       (next_controller_state[3]), .RB (n_9), .Q (controller_state[3]),
       .QB (n_137));
  SDFQM2RA \write_burst_count_reg[0] (.CK (clk), .D (n_89), .SD (n_92),
       .SE (n_369), .Q (n_369));
  DFZRM2RA \controller_state_reg[2] (.CK (clk), .D
       (next_controller_state[2]), .RB (n_9), .Q (controller_state[2]),
       .QB (n_138));
endmodule

